### ISSUE TITLE
Unsupported system page size on Asahi Linux

### ISSUE THREAD

**Issue by tmeijn** [hatoo/oha#658]
Hi! When I try to run this tool on M1 MacBook with Asahi Linux it fails:

```shell
❯ oha
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 56 bytes failed
fish: Job 1, 'oha' terminated by signal SIGABRT (Abort)
```

**Comment by hatoo** [comment]
Thanks for your report!

I think it is fixed. You can download the new build at https://github.com/hatoo/oha/actions/runs/12962765494

**Comment by tmeijn** [comment]
Hey @hatoo thanks for taking a stab at this! However it does not seem to fix it for my system:

```shell
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~/Downloads/oha-linux-arm64 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
❯ ./oha 
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 8192 bytes failed
Aborted (core dumped)
```

**Comment by hatoo** [comment]
Thanks, how about this?
https://github.com/hatoo/oha/actions/runs/12987145928

**Comment by tmeijn** [comment]
Works, awesome!

```shell
-----------------------------------------------------------------------------------------------------------------------------------------
~/Downloads/oha-linux-arm64(1) 
-----------------------------------------------------------------------------------------------------------------------------------------
❯ ./oha 
Ohayou(おはよう), HTTP load generator, inspired by rakyll/hey with tui animation.
```

**Comment by hatoo** [comment]
Thank you! 👍
